name: Build Router Plus APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: إعداد Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: إعداد Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: بناء APK
        run: gradle assembleDebug

      - name: حفظ APK
        uses: actions/upload-artifact@v4
        with:
          name: RouterPlus-APK
          path: app/build/outputs/apk/debug/app-debug.apk
